server:
  port: 9092
  servlet:
    context-path: /eric
mybatis:
  type-aliases-package: com.eric.serverservice.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    drive-class-name: com.mysql.jdbc.driver
  application:
    name: server-service
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.1.253:10086/eric/eureka, http://192.168.1.253:10087/eric/eureka
      defaultZone: http://192.168.1.253:10086/eric/eureka

    fetch-registry: true
    register-with-eureka: true
